/* Dummy data for the Browse (billboards) page — from templates/browse.html. */

export const BILLBOARDS = [
  {
    id: 1,
    title: 'Bandra Kurla Complex Unipole',
    city: 'Mumbai',
    area: 'BKC',
    type: 'Unipole',
    size: '60 × 30 ft',
    facing: 'North',
    footfall: '1,50,000/day',
    footfallNum: 150000,
    audience: 'Corporate, BFSI',
    traffic: 'City / Urban',
    tags: ['High Traffic', 'Premium'],
    price: '₹4.5L',
    priceNum: 450000,
    available: true,
    icon: 'city',
    rating: 4.8,
    reviews: 24,
    packages: { m1: '₹4.5L', m3: '₹12.5L', m6: '₹22L', m12: '₹38L' },
    mapX: '20%',
    mapY: '48%',
  },
  {
    id: 2,
    title: 'Powai Lake Digital Hoarding',
    city: 'Mumbai',
    area: 'Powai',
    type: 'LED Digital',
    size: '40 × 20 ft',
    facing: 'East',
    footfall: '80,000/day',
    footfallNum: 80000,
    audience: 'IT Professionals, Families',
    traffic: 'City / Urban',
    tags: ['Digital', 'High Traffic'],
    price: '₹3.2L',
    priceNum: 320000,
    available: true,
    icon: 'led',
    rating: 4.6,
    reviews: 18,
    packages: { m1: '₹3.2L', m3: '₹9L', m6: '₹16L', m12: '₹28L' },
    mapX: '22%',
    mapY: '46%',
  },
  {
    id: 3,
    title: 'MG Road Junction Gantry',
    city: 'Bengaluru',
    area: 'MG Road',
    type: 'Gantry',
    size: '80 × 15 ft',
    facing: 'Both Ways',
    footfall: '2,20,000/day',
    footfallNum: 220000,
    audience: 'Mixed Urban, Shoppers',
    traffic: 'City / Urban',
    tags: ['High Traffic', 'Premium', 'Gantry'],
    price: '₹7.8L',
    priceNum: 780000,
    available: false,
    icon: 'highway',
    rating: 4.9,
    reviews: 31,
    packages: { m1: '₹7.8L', m3: '₹22L', m6: '₹40L', m12: '₹72L' },
    mapX: '36%',
    mapY: '68%',
  },
  {
    id: 4,
    title: 'Connaught Place Static Hoarding',
    city: 'Delhi NCR',
    area: 'CP',
    type: 'Static Hoarding',
    size: '50 × 25 ft',
    facing: 'West',
    footfall: '3,00,000/day',
    footfallNum: 300000,
    audience: 'Tourists, Mixed',
    traffic: 'City / Urban',
    tags: ['High Traffic', 'Premium'],
    price: '₹5.2L',
    priceNum: 520000,
    available: true,
    icon: 'monument',
    rating: 4.7,
    reviews: 22,
    packages: { m1: '₹5.2L', m3: '₹14.5L', m6: '₹26L', m12: '₹46L' },
    mapX: '32%',
    mapY: '26%',
  },
  {
    id: 5,
    title: 'Cyber Towers Hyderabad LED',
    city: 'Hyderabad',
    area: 'Madhapur',
    type: 'LED Digital',
    size: '35 × 18 ft',
    facing: 'South',
    footfall: '1,00,000/day',
    footfallNum: 100000,
    audience: 'IT Professionals',
    traffic: 'City / Urban',
    tags: ['Digital', 'Premium'],
    price: '₹2.6L',
    priceNum: 260000,
    available: true,
    icon: 'digital',
    rating: 4.5,
    reviews: 13,
    packages: { m1: '₹2.6L', m3: '₹7.2L', m6: '₹13L', m12: '₹22L' },
    mapX: '40%',
    mapY: '59%',
  },
  {
    id: 6,
    title: 'BRTS Highway Billboard',
    city: 'Ahmedabad',
    area: 'SG Highway',
    type: 'Static Hoarding',
    size: '55 × 28 ft',
    facing: 'North',
    footfall: '90,000/day',
    footfallNum: 90000,
    audience: 'Commuters, Mixed',
    traffic: 'Highway',
    tags: ['Near Highway', 'High Traffic'],
    price: '₹1.5L',
    priceNum: 150000,
    available: true,
    icon: 'transit',
    rating: 4.3,
    reviews: 8,
    packages: { m1: '₹1.5L', m3: '₹4.2L', m6: '₹7.5L', m12: '₹13L' },
    mapX: '17%',
    mapY: '42%',
  },
  {
    id: 7,
    title: 'Anna Salai Bus Shelter',
    city: 'Chennai',
    area: 'Anna Salai',
    type: 'Bus Shelter',
    size: '12 × 5 ft',
    facing: 'Eastbound',
    footfall: '1,20,000/day',
    footfallNum: 120000,
    audience: 'Commuters, Shoppers',
    traffic: 'City / Urban',
    tags: ['High Traffic'],
    price: '₹95K',
    priceNum: 95000,
    available: true,
    icon: 'commercial',
    rating: 4.4,
    reviews: 11,
    packages: { m1: '₹95K', m3: '₹2.7L', m6: '₹4.8L', m12: '₹8.5L' },
    mapX: '38%',
    mapY: '74%',
  },
  {
    id: 8,
    title: 'Hebbal Flyover Unipole',
    city: 'Bengaluru',
    area: 'Hebbal',
    type: 'Unipole',
    size: '45 × 22 ft',
    facing: 'South',
    footfall: '88,000/day',
    footfallNum: 88000,
    audience: 'Highway Travelers, Commuters',
    traffic: 'Highway',
    tags: ['High Traffic', 'Near Highway'],
    price: '₹1.8L',
    priceNum: 180000,
    available: true,
    icon: 'highway',
    rating: 4.4,
    reviews: 9,
    packages: { m1: '₹1.8L', m3: '₹5L', m6: '₹9L', m12: '₹16L' },
    mapX: '37%',
    mapY: '70%',
  },
  {
    id: 9,
    title: 'Kothrud Junction LED',
    city: 'Pune',
    area: 'Kothrud',
    type: 'LED Digital',
    size: '30 × 15 ft',
    facing: 'West',
    footfall: '55,000/day',
    footfallNum: 55000,
    audience: 'Students, Shoppers',
    traffic: 'City / Urban',
    tags: ['Digital'],
    price: '₹2.8L',
    priceNum: 280000,
    available: true,
    icon: 'digital',
    rating: 4.5,
    reviews: 7,
    packages: { m1: '₹2.8L', m3: '₹7.8L', m6: '₹14L', m12: '₹24L' },
    mapX: '29%',
    mapY: '53%',
  },
  {
    id: 10,
    title: 'NH-44 Highway Hoarding',
    city: 'Hyderabad',
    area: 'Shamshabad',
    type: 'Static Hoarding',
    size: '60 × 30 ft',
    facing: 'East',
    footfall: '70,000/day',
    footfallNum: 70000,
    audience: 'Highway Travelers',
    traffic: 'Highway',
    tags: ['Near Highway', 'High Traffic'],
    price: '₹1.2L',
    priceNum: 120000,
    available: true,
    icon: 'transit',
    rating: 4.3,
    reviews: 6,
    packages: { m1: '₹1.2L', m3: '₹3.3L', m6: '₹6L', m12: '₹10.5L' },
    mapX: '41%',
    mapY: '61%',
  },
  {
    id: 11,
    title: 'Ashram Road Unipole',
    city: 'Ahmedabad',
    area: 'Ashram Road',
    type: 'Unipole',
    size: '50 × 25 ft',
    facing: 'North',
    footfall: '60,000/day',
    footfallNum: 60000,
    audience: 'Commuters, Mixed',
    traffic: 'City / Urban',
    tags: ['High Traffic'],
    price: '₹90K',
    priceNum: 90000,
    available: true,
    icon: 'metro',
    rating: 4.3,
    reviews: 4,
    packages: { m1: '₹90K', m3: '₹2.5L', m6: '₹4.5L', m12: '₹8L' },
    mapX: '18%',
    mapY: '44%',
  },
  {
    id: 12,
    title: 'T Nagar Mall Facade',
    city: 'Chennai',
    area: 'T Nagar',
    type: 'Building Wrap',
    size: '80 × 40 ft',
    facing: 'South',
    footfall: '2,00,000/day',
    footfallNum: 200000,
    audience: 'Shoppers, Mixed',
    traffic: 'Commercial Zone',
    tags: ['Premium', 'High Traffic'],
    price: '₹6.5L',
    priceNum: 650000,
    available: false,
    icon: 'retail',
    rating: 4.8,
    reviews: 16,
    packages: { m1: '₹6.5L', m3: '₹18L', m6: '₹32L', m12: '₹56L' },
    mapX: '39%',
    mapY: '76%',
  },
];

export const CITIES = [
  'Mumbai',
  'Bengaluru',
  'Pune',
  'Delhi NCR',
  'Hyderabad',
  'Chennai',
  'Ahmedabad',
];
export const TYPES = [
  'Static Hoarding',
  'LED Digital',
  'Unipole',
  'Gantry',
  'Bus Shelter',
  'Building Wrap',
];
export const TRAFFIC_ZONES = ['City / Urban', 'Highway', 'Commercial Zone', 'Residential Area'];
export const QUICK_TAGS = ['High Traffic', 'Premium', 'Near Highway', 'Digital', 'Gantry'];
export const SORTS = [
  { value: 'relevance', label: 'Relevance' },
  { value: 'price-asc', label: 'Price: Low to High' },
  { value: 'price-desc', label: 'Price: High to Low' },
  { value: 'footfall', label: 'Most Footfall' },
  { value: 'rating', label: 'Top Rated' },
];

/* 36×36 inline icons keyed by billboard.icon (rendered via dangerouslySetInnerHTML). */
export const ICON_SVG = {
  city: '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="1"/><path d="M8 4V2M16 4V2M3 9h18"/></svg>',
  led: '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',
  highway:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17l3-10 3 5 3-8 3 8 3-5 3 10"/><line x1="3" y1="21" x2="21" y2="21"/></svg>',
  monument:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 22 20 2 20"/></svg>',
  transit:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="6" width="22" height="13" rx="2"/><path d="M23 11H1"/><path d="M5 6V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1"/></svg>',
  commercial:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg>',
  urban:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 22V12h6v10M9 6h.01M15 6h.01M9 10h.01M15 10h.01"/></svg>',
  digital:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/><path d="M6 8h12M6 11h8"/></svg>',
  metro:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="2" width="14" height="20" rx="2"/><path d="M12 18h.01M9 6h6M9 10h6M9 14h3"/></svg>',
  retail:
    '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>',
  wall: '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="1"/><line x1="2" y1="10" x2="22" y2="10"/><line x1="2" y1="16" x2="22" y2="16"/><line x1="8" y1="4" x2="8" y2="10"/><line x1="14" y1="10" x2="14" y2="16"/><line x1="8" y1="16" x2="8" y2="20"/></svg>',
  road: '<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20L8 4M20 20l-4-16M12 4v4M12 12v4"/></svg>',
};

export const BOOKED_DAYS = [3, 7, 8, 9, 14, 15, 16, 17, 18, 21];
