-- Baseline schema. Portable across PostgreSQL (prod) and H2 in PostgreSQL mode (dev/test).
-- Replace this placeholder table with the real AdBasket schema as the domain grows.

CREATE TABLE sample_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sample_item (name) VALUES ('First sample');
INSERT INTO sample_item (name) VALUES ('Second sample');
