-- Role-specific registration data captured by the frontend onboarding wizards.
-- Portable across PostgreSQL (prod) and H2 in PostgreSQL mode (dev/test).

-- ── Advertiser ──────────────────────────────────────────────────────────────
CREATE TABLE advertiser_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    company_name        VARCHAR(150) NOT NULL,
    business_type       VARCHAR(80)  NOT NULL,
    website             VARCHAR(255),
    gst_number          VARCHAR(15),
    pan_number          VARCHAR(10),
    contact_designation VARCHAR(120) NOT NULL,
    contact_email       VARCHAR(180) NOT NULL,
    office_address      VARCHAR(500) NOT NULL,
    pincode             VARCHAR(6)   NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_advertiser_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_advertiser_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE advertiser_industries (
    profile_id BIGINT      NOT NULL,
    industry   VARCHAR(80) NOT NULL,
    CONSTRAINT fk_advertiser_industries_profile FOREIGN KEY (profile_id) REFERENCES advertiser_profiles (id) ON DELETE CASCADE
);

CREATE TABLE campaign_briefs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT        NOT NULL,
    title               VARCHAR(200)  NOT NULL,
    description         VARCHAR(2000) NOT NULL,
    target_audience     VARCHAR(500)  NOT NULL,
    target_location     VARCHAR(300)  NOT NULL,
    start_date          DATE          NOT NULL,
    duration            VARCHAR(50)   NOT NULL,
    budget_min_value    NUMERIC(14,2),
    budget_min_unit     VARCHAR(20),
    budget_max_value    NUMERIC(14,2),
    budget_max_unit     VARCHAR(20),
    flexible_budget     BOOLEAN       NOT NULL DEFAULT FALSE,
    quotations_required VARCHAR(20),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campaign_briefs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE campaign_brief_agency_prefs (
    brief_id   BIGINT      NOT NULL,
    preference VARCHAR(80) NOT NULL,
    CONSTRAINT fk_campaign_brief_prefs FOREIGN KEY (brief_id) REFERENCES campaign_briefs (id) ON DELETE CASCADE
);

-- ── Owner ───────────────────────────────────────────────────────────────────
CREATE TABLE owner_profiles (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT       NOT NULL,
    company_name           VARCHAR(150) NOT NULL,
    company_phone          VARCHAR(20),
    company_reg_number     VARCHAR(60),
    gst_number             VARCHAR(15),
    business_address_line1 VARCHAR(300) NOT NULL,
    business_address_line2 VARCHAR(300),
    business_pincode       VARCHAR(6)   NOT NULL,
    trade_license_no       VARCHAR(80),
    ownership_type         VARCHAR(60),
    regulatory_approvals   VARCHAR(120),
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_owner_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_owner_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE billboard_listings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    name             VARCHAR(150)  NOT NULL,
    pincode          VARCHAR(6)    NOT NULL,
    address          VARCHAR(500)  NOT NULL,
    landmark         VARCHAR(200),
    type             VARCHAR(60)   NOT NULL,
    width_ft         NUMERIC(8,2)  NOT NULL,
    height_ft        NUMERIC(8,2)  NOT NULL,
    ground_height_ft NUMERIC(8,2),
    facing           VARCHAR(60)   NOT NULL,
    traffic_type     VARCHAR(80)   NOT NULL,
    audience_type    VARCHAR(120)  NOT NULL,
    footfall         VARCHAR(60),
    start_price      NUMERIC(14,2) NOT NULL,
    min_booking      VARCHAR(50)   NOT NULL,
    discount_note    VARCHAR(500),
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_billboard_listings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ── Agency ──────────────────────────────────────────────────────────────────
CREATE TABLE agency_profiles (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT        NOT NULL,
    agency_name           VARCHAR(150)  NOT NULL,
    agency_type           VARCHAR(80)   NOT NULL,
    year_established      INTEGER       NOT NULL,
    years_experience      VARCHAR(40),
    tagline               VARCHAR(200),
    about                 VARCHAR(2000),
    website               VARCHAR(255),
    landline              VARCHAR(30),
    linkedin_url          VARCHAR(255),
    headquarters_pincode  VARCHAR(6)    NOT NULL,
    office_address        VARCHAR(500)  NOT NULL,
    contact_designation   VARCHAR(120)  NOT NULL,
    campaigns_completed   VARCHAR(40),
    pricing_model         VARCHAR(80),
    min_tender_budget     VARCHAR(60),
    geo_coverage          VARCHAR(80),
    coverage_cities       VARCHAR(300),
    reg_number            VARCHAR(60),
    gst_number            VARCHAR(15),
    pan_number            VARCHAR(10),
    key_clients           VARCHAR(500),
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agency_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_agency_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE agency_services (
    profile_id BIGINT       NOT NULL,
    service    VARCHAR(120) NOT NULL,
    CONSTRAINT fk_agency_services_profile FOREIGN KEY (profile_id) REFERENCES agency_profiles (id) ON DELETE CASCADE
);
CREATE TABLE agency_industries (
    profile_id BIGINT      NOT NULL,
    industry   VARCHAR(80) NOT NULL,
    CONSTRAINT fk_agency_industries_profile FOREIGN KEY (profile_id) REFERENCES agency_profiles (id) ON DELETE CASCADE
);
CREATE TABLE agency_expertise_tags (
    profile_id BIGINT      NOT NULL,
    tag        VARCHAR(80) NOT NULL,
    CONSTRAINT fk_agency_expertise_profile FOREIGN KEY (profile_id) REFERENCES agency_profiles (id) ON DELETE CASCADE
);
CREATE TABLE agency_languages (
    profile_id BIGINT      NOT NULL,
    language   VARCHAR(40) NOT NULL,
    CONSTRAINT fk_agency_languages_profile FOREIGN KEY (profile_id) REFERENCES agency_profiles (id) ON DELETE CASCADE
);
CREATE TABLE agency_portfolio_items (
    profile_id BIGINT       NOT NULL,
    title      VARCHAR(200) NOT NULL,
    meta       VARCHAR(300),
    CONSTRAINT fk_agency_portfolio_profile FOREIGN KEY (profile_id) REFERENCES agency_profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_campaign_briefs_user   ON campaign_briefs (user_id);
CREATE INDEX idx_billboard_listings_user ON billboard_listings (user_id);
