-- V3__normalize_schema.sql
-- Forward-only normalization: standardize booleans/timestamps, create addresses table, link foreign keys, and drop legacy columns.

-- 1. Standardize column names on users
ALTER TABLE users RENAME COLUMN password_hash TO password;
ALTER TABLE users RENAME COLUMN enabled TO is_enabled;
ALTER TABLE users RENAME COLUMN email_verified TO is_email_verified;
ALTER TABLE users RENAME COLUMN created_at TO created_ts;
ALTER TABLE users RENAME COLUMN updated_at TO updated_ts;

-- 2. Standardize column names on refresh_tokens
ALTER TABLE refresh_tokens RENAME COLUMN expires_at TO expiry_ts;
ALTER TABLE refresh_tokens RENAME COLUMN revoked TO is_revoked;
ALTER TABLE refresh_tokens RENAME COLUMN created_at TO created_ts;

-- 3. Create standalone addresses table
CREATE TABLE addresses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line1      VARCHAR(300) NOT NULL,
    line2      VARCHAR(300),
    landmark   VARCHAR(200),
    city       VARCHAR(100) NOT NULL,
    state      VARCHAR(100) NOT NULL,
    pincode    VARCHAR(6)   NOT NULL,
    created_ts TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_ts TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_addresses_pincode ON addresses (pincode);

-- 4. Update advertiser_profiles
ALTER TABLE advertiser_profiles RENAME COLUMN contact_email TO email;
ALTER TABLE advertiser_profiles RENAME COLUMN created_at TO created_ts;
ALTER TABLE advertiser_profiles RENAME COLUMN updated_at TO updated_ts;
ALTER TABLE advertiser_profiles ADD CONSTRAINT uq_advertiser_profiles_gst UNIQUE (gst_number);

ALTER TABLE advertiser_profiles ADD COLUMN address_id BIGINT;
-- Drop legacy columns
ALTER TABLE advertiser_profiles DROP COLUMN office_address;
ALTER TABLE advertiser_profiles DROP COLUMN pincode;

-- Make address_id NOT NULL and add foreign key constraint
ALTER TABLE advertiser_profiles ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE advertiser_profiles ADD CONSTRAINT fk_advertiser_profiles_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_advertiser_profiles_address ON advertiser_profiles (address_id);

-- 5. Update campaign_briefs
ALTER TABLE campaign_briefs ADD COLUMN end_date DATE NOT NULL;
ALTER TABLE campaign_briefs RENAME COLUMN created_at TO created_ts;

-- 6. Update owner_profiles
ALTER TABLE owner_profiles RENAME COLUMN created_at TO created_ts;
ALTER TABLE owner_profiles RENAME COLUMN updated_at TO updated_ts;

ALTER TABLE owner_profiles ADD COLUMN address_id BIGINT;
-- Drop legacy columns
ALTER TABLE owner_profiles DROP COLUMN business_address_line1;
ALTER TABLE owner_profiles DROP COLUMN business_address_line2;
ALTER TABLE owner_profiles DROP COLUMN business_pincode;

-- Make address_id NOT NULL and add foreign key constraint
ALTER TABLE owner_profiles ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE owner_profiles ADD CONSTRAINT fk_owner_profiles_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_owner_profiles_address ON owner_profiles (address_id);

-- 7. Update billboard_listings
ALTER TABLE billboard_listings RENAME COLUMN created_at TO created_ts;

ALTER TABLE billboard_listings ADD COLUMN address_id BIGINT;
-- Drop legacy columns
ALTER TABLE billboard_listings DROP COLUMN pincode;
ALTER TABLE billboard_listings DROP COLUMN address;
ALTER TABLE billboard_listings DROP COLUMN landmark;

-- Make address_id NOT NULL and add foreign key constraint
ALTER TABLE billboard_listings ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE billboard_listings ADD CONSTRAINT fk_billboard_listings_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_billboard_listings_address ON billboard_listings (address_id);

-- 8. Update agency_profiles
ALTER TABLE agency_profiles RENAME COLUMN landline TO contact_no;
ALTER TABLE agency_profiles RENAME COLUMN created_at TO created_ts;
ALTER TABLE agency_profiles RENAME COLUMN updated_at TO updated_ts;

ALTER TABLE agency_profiles ADD COLUMN address_id BIGINT;
-- Drop legacy columns
ALTER TABLE agency_profiles DROP COLUMN headquarters_pincode;
ALTER TABLE agency_profiles DROP COLUMN office_address;

-- Make address_id NOT NULL and add foreign key constraint
ALTER TABLE agency_profiles ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE agency_profiles ADD CONSTRAINT fk_agency_profiles_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_agency_profiles_address ON agency_profiles (address_id);