-- V3__normalize_schema.sql
-- Forward-only normalization: standardize booleans/timestamps, create addresses table,
-- backfill legacy addresses and required fields, link foreign keys, and drop legacy columns.

-- 1. Standardize column names on users
ALTER TABLE users RENAME COLUMN password_hash TO password;
ALTER TABLE users RENAME COLUMN enabled TO is_enabled;
ALTER TABLE users RENAME COLUMN email_verified TO is_email_verified;
ALTER TABLE users RENAME COLUMN created_at TO created_ts;
ALTER TABLE users RENAME COLUMN updated_at TO updated_ts;

-- 2. Standardize column names on refresh_tokens
ALTER TABLE refresh_tokens RENAME COLUMN expires_at TO expiry_ts;
ALTER TABLE refresh_tokens RENAME COLUMN revoked TO is_revoked;
ALTER TABLE refresh_tokens RENAME COLUMN created_at TO created_ts;

-- 3. Create standalone addresses table with temporary tracking columns for backfilling
CREATE TABLE addresses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line1             VARCHAR(300) NOT NULL,
    line2             VARCHAR(300),
    landmark          VARCHAR(200),
    city              VARCHAR(100) NOT NULL,
    state             VARCHAR(100) NOT NULL,
    pincode           VARCHAR(6)   NOT NULL,
    created_ts        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_ts        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temp_source_table VARCHAR(50),
    temp_source_id    BIGINT
);

CREATE INDEX idx_addresses_pincode ON addresses (pincode);

-- 4. Update advertiser_profiles
ALTER TABLE advertiser_profiles RENAME COLUMN contact_email TO email;
ALTER TABLE advertiser_profiles RENAME COLUMN created_at TO created_ts;
ALTER TABLE advertiser_profiles RENAME COLUMN updated_at TO updated_ts;

-- Sanitize empty GST strings to NULL before adding unique constraint
UPDATE advertiser_profiles SET gst_number = NULL WHERE TRIM(gst_number) = '';
ALTER TABLE advertiser_profiles ADD CONSTRAINT uq_advertiser_profiles_gst UNIQUE (gst_number);

-- Add nullable address_id
ALTER TABLE advertiser_profiles ADD COLUMN address_id BIGINT;

-- Backfill addresses from legacy advertiser_profiles
-- If office_address > 300 chars, overflow into line2 to prevent truncation data loss
INSERT INTO addresses (line1, line2, landmark, city, state, pincode, created_ts, updated_ts, temp_source_table, temp_source_id)
SELECT 
    COALESCE(NULLIF(TRIM(SUBSTRING(office_address, 1, 300)), ''), 'Address Not Provided'),
    NULLIF(TRIM(SUBSTRING(office_address, 301, 200)), ''),
    NULL,
    'Unknown',
    'Unknown',
    COALESCE(NULLIF(TRIM(pincode), ''), '000000'),
    created_ts,
    updated_ts,
    'advertiser_profiles',
    id
FROM advertiser_profiles;

-- Link backfilled address_id (deterministic 1:1 join on primary key)
UPDATE advertiser_profiles ap
SET address_id = (
    SELECT a.id FROM addresses a
    WHERE a.temp_source_table = 'advertiser_profiles' AND a.temp_source_id = ap.id
);

-- Enforce NOT NULL and foreign key constraint
ALTER TABLE advertiser_profiles ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE advertiser_profiles ADD CONSTRAINT fk_advertiser_profiles_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_advertiser_profiles_address ON advertiser_profiles (address_id);

-- Drop legacy columns
ALTER TABLE advertiser_profiles DROP COLUMN office_address;
ALTER TABLE advertiser_profiles DROP COLUMN pincode;

-- 5. Update campaign_briefs
ALTER TABLE campaign_briefs ADD COLUMN end_date DATE;

-- Backfill end_date from historical duration or default to start_date + 30 days
UPDATE campaign_briefs 
SET end_date = CASE
    WHEN LOWER(duration) LIKE '%15 day%' THEN start_date + 15
    WHEN LOWER(duration) LIKE '%1 month%' OR LOWER(duration) LIKE '%30 day%' THEN start_date + 30
    WHEN LOWER(duration) LIKE '%2 month%' OR LOWER(duration) LIKE '%60 day%' THEN start_date + 60
    WHEN LOWER(duration) LIKE '%3 month%' OR LOWER(duration) LIKE '%90 day%' THEN start_date + 90
    WHEN LOWER(duration) LIKE '%6 month%' THEN start_date + 180
    WHEN LOWER(duration) LIKE '%1 year%' THEN start_date + 365
    ELSE start_date + 30
END;

-- Enforce NOT NULL constraint
ALTER TABLE campaign_briefs ALTER COLUMN end_date SET NOT NULL;
ALTER TABLE campaign_briefs RENAME COLUMN created_at TO created_ts;

-- 6. Update owner_profiles
ALTER TABLE owner_profiles RENAME COLUMN created_at TO created_ts;
ALTER TABLE owner_profiles RENAME COLUMN updated_at TO updated_ts;

-- Add nullable address_id
ALTER TABLE owner_profiles ADD COLUMN address_id BIGINT;

-- Backfill addresses from legacy owner_profiles
INSERT INTO addresses (line1, line2, landmark, city, state, pincode, created_ts, updated_ts, temp_source_table, temp_source_id)
SELECT 
    COALESCE(NULLIF(TRIM(business_address_line1), ''), 'Address Not Provided'),
    NULLIF(TRIM(business_address_line2), ''),
    NULL,
    'Unknown',
    'Unknown',
    COALESCE(NULLIF(TRIM(business_pincode), ''), '000000'),
    created_ts,
    updated_ts,
    'owner_profiles',
    id
FROM owner_profiles;

-- Link backfilled address_id (deterministic 1:1 join on primary key)
UPDATE owner_profiles op
SET address_id = (
    SELECT a.id FROM addresses a
    WHERE a.temp_source_table = 'owner_profiles' AND a.temp_source_id = op.id
);

-- Enforce NOT NULL and foreign key constraint
ALTER TABLE owner_profiles ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE owner_profiles ADD CONSTRAINT fk_owner_profiles_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_owner_profiles_address ON owner_profiles (address_id);

-- Drop legacy columns
ALTER TABLE owner_profiles DROP COLUMN business_address_line1;
ALTER TABLE owner_profiles DROP COLUMN business_address_line2;
ALTER TABLE owner_profiles DROP COLUMN business_pincode;

-- 7. Update billboard_listings
ALTER TABLE billboard_listings RENAME COLUMN created_at TO created_ts;

-- Add nullable address_id
ALTER TABLE billboard_listings ADD COLUMN address_id BIGINT;

-- Backfill addresses from legacy billboard_listings
-- If address > 300 chars, overflow into line2 to prevent truncation data loss
INSERT INTO addresses (line1, line2, landmark, city, state, pincode, created_ts, updated_ts, temp_source_table, temp_source_id)
SELECT 
    COALESCE(NULLIF(TRIM(SUBSTRING(address, 1, 300)), ''), 'Address Not Provided'),
    NULLIF(TRIM(SUBSTRING(address, 301, 200)), ''),
    NULLIF(TRIM(landmark), ''),
    'Unknown',
    'Unknown',
    COALESCE(NULLIF(TRIM(pincode), ''), '000000'),
    created_ts,
    created_ts,
    'billboard_listings',
    id
FROM billboard_listings;

-- Link backfilled address_id (deterministic 1:1 join on primary key)
UPDATE billboard_listings bl
SET address_id = (
    SELECT a.id FROM addresses a
    WHERE a.temp_source_table = 'billboard_listings' AND a.temp_source_id = bl.id
);

-- Enforce NOT NULL and foreign key constraint
ALTER TABLE billboard_listings ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE billboard_listings ADD CONSTRAINT fk_billboard_listings_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_billboard_listings_address ON billboard_listings (address_id);

-- Drop legacy columns
ALTER TABLE billboard_listings DROP COLUMN pincode;
ALTER TABLE billboard_listings DROP COLUMN address;
ALTER TABLE billboard_listings DROP COLUMN landmark;

-- 8. Update agency_profiles
ALTER TABLE agency_profiles RENAME COLUMN landline TO contact_no;
ALTER TABLE agency_profiles RENAME COLUMN created_at TO created_ts;
ALTER TABLE agency_profiles RENAME COLUMN updated_at TO updated_ts;

-- Add nullable address_id
ALTER TABLE agency_profiles ADD COLUMN address_id BIGINT;

-- Backfill addresses from legacy agency_profiles
-- If office_address > 300 chars, overflow into line2 to prevent truncation data loss
INSERT INTO addresses (line1, line2, landmark, city, state, pincode, created_ts, updated_ts, temp_source_table, temp_source_id)
SELECT 
    COALESCE(NULLIF(TRIM(SUBSTRING(office_address, 1, 300)), ''), 'Address Not Provided'),
    NULLIF(TRIM(SUBSTRING(office_address, 301, 200)), ''),
    NULL,
    'Unknown',
    'Unknown',
    COALESCE(NULLIF(TRIM(headquarters_pincode), ''), '000000'),
    created_ts,
    updated_ts,
    'agency_profiles',
    id
FROM agency_profiles;

-- Link backfilled address_id (deterministic 1:1 join on primary key)
UPDATE agency_profiles agp
SET address_id = (
    SELECT a.id FROM addresses a
    WHERE a.temp_source_table = 'agency_profiles' AND a.temp_source_id = agp.id
);

-- Make address_id NOT NULL and add foreign key constraint
ALTER TABLE agency_profiles ALTER COLUMN address_id SET NOT NULL;
ALTER TABLE agency_profiles ADD CONSTRAINT fk_agency_profiles_address 
    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE CASCADE;
CREATE INDEX idx_agency_profiles_address ON agency_profiles (address_id);

-- Drop legacy columns
ALTER TABLE agency_profiles DROP COLUMN headquarters_pincode;
ALTER TABLE agency_profiles DROP COLUMN office_address;

-- 9. Clean up temporary migration tracking columns from addresses
ALTER TABLE addresses DROP COLUMN temp_source_table;
ALTER TABLE addresses DROP COLUMN temp_source_id;