-- ── Shared Notifications ──────────────────────────────────────────────────────
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    title       VARCHAR(150) NOT NULL,
    message     VARCHAR(500) NOT NULL,
    category    VARCHAR(50)  NOT NULL,
    tone        VARCHAR(20)  NOT NULL,
    target_url  VARCHAR(255),
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_ts  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_ts DESC);
CREATE INDEX idx_notifications_user_read ON notifications(user_id, is_read);
